<?php

namespace Modules\Payment\Enums;

enum GatewayErrorCode: string
{
    case NOT_CONFIGURED = 'GATEWAY_NOT_CONFIGURED';
    case INVALID_REQUEST = 'GATEWAY_INVALID_REQUEST';
    case AUTHENTICATION_FAILED = 'GATEWAY_AUTHENTICATION_FAILED';
    case DECLINED = 'GATEWAY_DECLINED';
    case RATE_LIMITED = 'GATEWAY_RATE_LIMITED';
    case UNAVAILABLE = 'GATEWAY_UNAVAILABLE';
    case INVALID_RESPONSE = 'GATEWAY_INVALID_RESPONSE';
}
